name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Build
        run: go build -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@latest

      - name: Check code formatting using gofmt
        uses: Jerome1337/gofmt-action@latest

      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
